### ISSUE TITLE
errand should dump values.yml or k8s manifest.yml to help manual troubleshooting

### ISSUE THREAD

**Issue by poblin-orange** [orange-cloudfoundry/helm-kubectl-boshrelease#15]
In case of failure, the errand log does not give any details on the manifest/values applied, making it harder to reproduce and troubleshoot manually

**Comment by obeyler** [comment]
you can jump into errand and replay it easily 
sudo -i
/var/vcap/jobs/action/bin/source set_env
then replay the action who has failed
